### ISSUE TITLE
keys contains encapsulated keys

### ISSUE THREAD

**Issue by Natim** [vladikoff/fxa-crypto-relier#8]
Actual result:

![oups](https://user-images.githubusercontent.com/229453/32047584-af52ff3c-ba46-11e7-84b5-9672721a692a.png)

We should have only one level I guess.

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/notes/pull/313/commits/ce126705abef379304569cbfe84a0440e3ef54b5
